<a href="https://colab.research.google.com/github/araffin/rl-tutorial-jnrr19/blob/master/2_gym_wrappers_saving_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stable Baselines Tutorial - Gym wrappers, saving and loading models

Github repo: https://github.com/araffin/rl-tutorial-jnrr19

Stable-Baselines: https://github.com/hill-a/stable-baselines

Documentation: https://stable-baselines.readthedocs.io/en/master/

RL Baselines zoo: https://github.com/araffin/rl-baselines-zoo


## Introduction

In this notebook, you will learn how to use *Gym Wrappers* which allow to do monitoring, normalization, limit the number of steps, feature augmentation, ...


You will also see the *loading* and *saving* functions, and how to read the outputed files for possible exporting.

## Install Dependencies and Stable Baselines Using Pip

In [0]:
# !apt install swig
# !pip install stable-baselines[mpi]==2.8.0
# # Stable Baselines only supports tensorflow 1.x for now
# %tensorflow_version 1.x

In [1]:
%load_ext autoreload
%autoreload 2
try:
    %%tensorflow_version 1.x
except:
    pass

import os
import sys
lib_path = os.path.abspath('../..')
print('inserting the following to path',lib_path)
if lib_path not in sys.path:
    sys.path.insert(0,lib_path)
print(sys.path)

inserting the following to path /home/guy/workspace/study/remote/stable-baselines
['/home/guy/workspace/study/remote/stable-baselines/my_colabs/jnrr19', '/home/guy/workspace/study/remote/stable-baselines/my_colabs/jnrr19', '/home/guy/workspace/study/remote/agents', '/home/guy/workspace/study/remote/stable-baselines', '/home/guy/anaconda3/envs/rl15/lib/python37.zip', '/home/guy/anaconda3/envs/rl15/lib/python3.7', '/home/guy/anaconda3/envs/rl15/lib/python3.7/lib-dynload', '', '/home/guy/anaconda3/envs/rl15/lib/python3.7/site-packages', '/home/guy/anaconda3/envs/rl15/lib/python3.7/site-packages/IPython/extensions', '/home/guy/.ipython']


In [2]:
# Filter tensorflow version warnings
# https://stackoverflow.com/questions/40426502/is-there-a-way-to-suppress-the-messages-tensorflow-prints/40426709
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # or any {'0', '1', '2'}
import warnings
# https://stackoverflow.com/questions/15777951/how-to-suppress-pandas-future-warning
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=Warning)
import tensorflow as tf
tf.get_logger().setLevel('INFO')
tf.autograph.set_verbosity(0)
import logging
tf.get_logger().setLevel(logging.ERROR)

In [12]:
# sys.path.pop(0)
# print(sys.path)

['/home/guy/anaconda3/envs/rl15/lib/python37.zip', '/home/guy/anaconda3/envs/rl15/lib/python3.7', '/home/guy/anaconda3/envs/rl15/lib/python3.7/lib-dynload', '', '/home/guy/anaconda3/envs/rl15/lib/python3.7/site-packages', '/home/guy/anaconda3/envs/rl15/lib/python3.7/site-packages/IPython/extensions', '/home/guy/.ipython']


In [3]:
import gym
from stable_baselines import A2C, SAC, PPO2, TD3

In [4]:
!pwd

/home/guy/workspace/study/remote/stable-baselines/my_colabs/jnrr19


# Saving and loading

Saving and loading stable-baselines models is straightforward: you can directly call `.save()` and `.load()` on the models.

In [5]:
import os

# Create save dir
save_dir = "/tmp/gym/"
os.makedirs(save_dir, exist_ok=True)

model = PPO2('MlpPolicy', 'Pendulum-v0', verbose=0).learn(8000)
# The model will be saved under PPO2_tutorial.zip
model.save(save_dir + "/PPO2_tutorial")

# sample an observation from the environment
obs = model.env.observation_space.sample()

# Check prediction before saving
print("pre saved", model.predict(obs, deterministic=True))

del model # delete trained model to demonstrate loading

loaded_model = PPO2.load(save_dir + "/PPO2_tutorial")
# Check that the prediction is the same after loading (for the same observation)
print("loaded", loaded_model.predict(obs, deterministic=True))

pre saved (array([-0.05531978], dtype=float32), None)
loaded (array([-0.05531978], dtype=float32), None)


Saving in stable-baselines is quite powerful, as you save the training hyperparameters, with the current weights. This means in practice, you can simply load a custom model, without redefining the parameters, and continue learning.

The loading function can also update the model's class variables when loading.

In [17]:
import os
from stable_baselines.common.vec_env import DummyVecEnv

# Create save dir
save_dir = "/tmp/gym/"
os.makedirs(save_dir, exist_ok=True)

model = A2C('MlpPolicy', 'Pendulum-v0', verbose=0, gamma=0.9, n_steps=20).learn(8000)
# The model will be saved under A2C_tutorial.zip
model.save(save_dir + "/A2C_tutorial")

del model # delete trained model to demonstrate loading

# load the model, and when loading set verbose to 1
loaded_model = A2C.load(save_dir + "/A2C_tutorial", verbose=1)

# show the save hyperparameters
print("loaded:", "gamma =", loaded_model.gamma, "n_steps =", loaded_model.n_steps)

# as the environment is not serializable, we need to set a new instance of the environment
loaded_model.set_env(DummyVecEnv([lambda: gym.make('Pendulum-v0')]))
# and continue training
loaded_model.learn(8000)




Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Loading a model without an environment, this model cannot be trained until it has a valid environment.
loaded: gamma = 0.9 n_steps = 20
---------------------------------
| explained_variance | -0.00602 |
| fps                | 88       |
| nupdates           | 1        |
| policy_entropy     | 1.42     |
| total_timesteps    | 20       |
| value_loss         | 1.85e+03 |
---------------------------------
---------------------------------
| explained_variance | -0.0451  |
| fps                | 524      |
| nupdates           | 100      |
| policy_entropy     | 1.42     |
| total_timesteps    | 2000     |
| value_loss         | 759      |
---------------------------------
---------------------------------
| explained_variance | 0.00915  |
| fps                | 534      |
| nupdates           | 200      |
| policy_entropy     | 1.42     |
| total_timesteps    | 4000  

# Gym and VecEnv wrappers

## Anatomy of a gym wrapper

A gym wrapper follows the [gym](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html) interface: it has a `reset()` and `step()` method.

Because a wrapper is *around* an environment, we can access it with `self.env`, this allow to easily interact with it without modifying the original env.
There are many wrappers that have been predefined, for a complete list refer to [gym documentation](https://github.com/openai/gym/tree/master/gym/wrappers)

In [18]:
class CustomWrapper(gym.Wrapper):
  """
  :param env: (gym.Env) Gym environment that will be wrapped
  """
  def __init__(self, env):
    # Call the parent constructor, so we can access self.env later
    super(CustomWrapper, self).__init__(env)
  
  def reset(self):
    """
    Reset the environment 
    """
    obs = self.env.reset()
    return obs

  def step(self, action):
    """
    :param action: ([float] or int) Action taken by the agent
    :return: (np.ndarray, float, bool, dict) observation, reward, is the episode over?, additional informations
    """
    obs, reward, done, info = self.env.step(action)
    return obs, reward, done, info


## First example: limit the episode length

One practical use case of a wrapper is when you want to limit the number of steps by episode, for that you will need to overwrite the `done` signal when the limit is reached. It is also a good practice to pass that information in the `info` dictionnary.

In [19]:
class TimeLimitWrapper(gym.Wrapper):
  """
  :param env: (gym.Env) Gym environment that will be wrapped
  :param max_steps: (int) Max number of steps per episode
  """
  def __init__(self, env, max_steps=100):
    # Call the parent constructor, so we can access self.env later
    super(TimeLimitWrapper, self).__init__(env)
    self.max_steps = max_steps
    # Counter of steps per episode
    self.current_step = 0
  
  def reset(self):
    """
    Reset the environment 
    """
    # Reset the counter
    self.current_step = 0
    return self.env.reset()

  def step(self, action):
    """
    :param action: ([float] or int) Action taken by the agent
    :return: (np.ndarray, float, bool, dict) observation, reward, is the episode over?, additional informations
    """
    self.current_step += 1
    obs, reward, done, info = self.env.step(action)
    # Overwrite the done signal when 
    if self.current_step >= self.max_steps:
        done = True
        # Update the info dict to signal that the limit was exceeded
        info['time_limit_reached'] = True
    return obs, reward, done, info


#### Test the wrapper

In [20]:
from gym.envs.classic_control.pendulum import PendulumEnv

# Here we create the environment directly because gym.make() already wrap the environement in a TimeLimit wrapper otherwise
env = PendulumEnv()
# Wrap the environment
env = TimeLimitWrapper(env, max_steps=100)

In [21]:
obs = env.reset()
done = False
n_steps = 0
while not done:
    # Take random actions
    random_action = env.action_space.sample()
    obs, reward, done, info = env.step(random_action)
    n_steps += 1

print(n_steps, info)

100 {'time_limit_reached': True}


In practice, `gym` already have a wrapper for that named `TimeLimit` (`gym.wrappers.TimeLimit`) that is used by most environments.

## Second example: normalize actions

It is usually a good idea to normalize observations and actions before giving it to the agent, this prevent [hard to debug issue](https://github.com/hill-a/stable-baselines/issues/473).

In this example, we are going to normalize the action space of *Pendulum-v0* so it lies in [-1, 1] instead of [-2, 2].

Note: here we are dealing with continuous actions, hence the `gym.Box` space

In [22]:
import numpy as np

class NormalizeActionWrapper(gym.Wrapper):
    """
    :param env: (gym.Env) Gym environment that will be wrapped
    """
    def __init__(self, env):
        # Retrieve the action space
        action_space = env.action_space
        assert isinstance(action_space, gym.spaces.Box), "This wrapper only works with continuous action space (spaces.Box)"
        # Retrieve the max/min values
        self.low, self.high = action_space.low, action_space.high

        # We modify the action space, so all actions will lie in [-1, 1]
        env.action_space = gym.spaces.Box(low=-1, high=1, shape=action_space.shape, dtype=np.float32)

        # Call the parent constructor, so we can access self.env later
        super(NormalizeActionWrapper, self).__init__(env)
  
    def rescale_action(self, scaled_action):
        """
        Rescale the action from [-1, 1] to [low, high]
        (no need for symmetric action space)
        :param scaled_action: (np.ndarray)
        :return: (np.ndarray)
        """
        return self.low + (0.5 * (scaled_action + 1.0) * (self.high -  self.low))

    def reset(self):
        """
        Reset the environment 
        """
        # Reset the counter
        return self.env.reset()

    def step(self, action):
        """
        :param action: ([float] or int) Action taken by the agent
        :return: (np.ndarray, float, bool, dict) observation, reward, is the episode over?, additional informations
        """
        # Rescale action from [-1, 1] to original [low, high] interval
        rescaled_action = self.rescale_action(action)
        obs, reward, done, info = self.env.step(rescaled_action)
        return obs, reward, done, info

#### Test before rescaling actions

In [23]:
original_env = gym.make("Pendulum-v0")

print(original_env.action_space.low)
for _ in range(10):
    print(original_env.action_space.sample())

[-2.]
[-1.7846217]
[-0.95488584]
[-1.3837284]
[-1.0874054]
[-0.9217721]
[0.7168553]
[-1.9694351]
[1.7232076]
[0.64138883]
[-1.3491364]


#### Test the NormalizeAction wrapper

In [24]:
env = NormalizeActionWrapper(gym.make("Pendulum-v0"))

print(env.action_space.low)

for _ in range(10):
    print(env.action_space.sample())

[-1.]
[-0.50132984]
[0.7377853]
[0.3500782]
[-0.5791502]
[0.41801283]
[0.34071988]
[-0.02350207]
[-0.24232079]
[-0.30819535]
[0.33877748]


#### Test with a RL algorithm

We are going to use the Monitor wrapper of stable baselines, wich allow to monitor training stats (mean episode reward, mean episode length)

In [34]:
from stable_baselines.bench import Monitor
from stable_baselines.common.vec_env import DummyVecEnv

In [35]:
env = Monitor(gym.make('Pendulum-v0'), filename=None, allow_early_resets=True)
env = DummyVecEnv([lambda: env])

In [36]:
model = A2C("MlpPolicy", env, verbose=1).learn(int(1000))

---------------------------------
| explained_variance | 0.172    |
| fps                | 23       |
| nupdates           | 1        |
| policy_entropy     | 1.42     |
| total_timesteps    | 5        |
| value_loss         | 5.69     |
---------------------------------
----------------------------------
| ep_len_mean        | 200       |
| ep_reward_mean     | -1.03e+03 |
| explained_variance | 0.00161   |
| fps                | 356       |
| nupdates           | 100       |
| policy_entropy     | 1.42      |
| total_timesteps    | 500       |
| value_loss         | 1.03e+03  |
----------------------------------
----------------------------------
| ep_len_mean        | 200       |
| ep_reward_mean     | -1.15e+03 |
| explained_variance | 0.0301    |
| fps                | 381       |
| nupdates           | 200       |
| policy_entropy     | 1.42      |
| total_timesteps    | 1000      |
| value_loss         | 37.3      |
----------------------------------


With the action wrapper

In [39]:
normalized_env = Monitor(gym.make('Pendulum-v0'), filename=None, allow_early_resets=True)
# Note that we can use multiple wrappers
normalized_env = NormalizeActionWrapper(normalized_env)
normalized_env = DummyVecEnv([lambda: normalized_env])

In [40]:
model_2 = A2C("MlpPolicy", normalized_env, verbose=1).learn(int(1000))

----------------------------------
| explained_variance | -0.000478 |
| fps                | 23        |
| nupdates           | 1         |
| policy_entropy     | 1.42      |
| total_timesteps    | 5         |
| value_loss         | 794       |
----------------------------------
---------------------------------
| explained_variance | -0.00054 |
| fps                | 342      |
| nupdates           | 100      |
| policy_entropy     | 1.42     |
| total_timesteps    | 500      |
| value_loss         | 974      |
---------------------------------
---------------------------------
| explained_variance | 0.324    |
| fps                | 364      |
| nupdates           | 200      |
| policy_entropy     | 1.42     |
| total_timesteps    | 1000     |
| value_loss         | 0.405    |
---------------------------------


## Additional wrappers: VecEnvWrappers

In the same vein as gym wrappers, stable baselines provide wrappers for `VecEnv`. Among the different that exist (and you can create your own), you should know: 

- VecNormalize: it computes a running mean and standard deviation to normalize observation and returns
- VecFrameStack: it stacks several consecutive observations (useful to integrate time in the observation, e.g. sucessive frame of an atari game)

More info in the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#wrappers)

Note: when using `VecNormalize` wrapper, you must save the running mean and std along with the model, otherwise you will not get proper results when loading the agent again. If you use the [rl zoo](https://github.com/araffin/rl-baselines-zoo), this is done automatically

In [41]:
from stable_baselines.common.vec_env import VecNormalize, VecFrameStack

env = DummyVecEnv([lambda: gym.make("Pendulum-v0")])
normalized_vec_env = VecNormalize(env)

In [42]:
obs = normalized_vec_env.reset()
for _ in range(10):
    action = [normalized_vec_env.action_space.sample()]
    obs, reward, _, _ = normalized_vec_env.step(action)
    print(obs, reward)

[[0.00706301 0.00065785 0.0036319 ]] [-1.6527573]
[[-0.12649035  0.91515796  0.9982918 ]] [-1.1853163]
[[-0.33028482  1.14652276  0.04495299]] [-1.4915196]
[[-0.72848758  1.36970605  1.17097443]] [-0.86195666]
[[-1.22933531  1.5279819   1.54329918]] [-1.0433859]
[[-1.65023619  1.65245472  1.72164534]] [-1.1189717]
[[-1.83378912  1.6824586   1.35315674]] [-1.1787472]
[[-1.98045156  1.73175757  1.57274686]] [-0.9577793]
[[-2.08982887  1.77412413  1.65305009]] [-0.96715295]
[[-2.19479001  1.81993924  1.81373232]] [-0.94818145]


## Exercise: code you own monitor wrapper

Now that you know how does a wrapper work and what you can do with it, it's time to experiment.

The goal here is to create a wrapper that will monitor the training progress, storing both the episode reward (sum of reward for one episode) and episode length (number of steps in for the last episode).

You will return those values using the `info` dict after each end of episode.

In [83]:
from IPython.core.debugger import set_trace

In [91]:
class MyMonitorWrapper2(gym.Wrapper):
  """
  :param env: (gym.Env) Gym environment that will be wrapped
  """
  def __init__(self, env):
    # Call the parent constructor, so we can access self.env later
    super(MyMonitorWrapper2, self).__init__(env)
    # === YOUR CODE HERE ===#
    # Initialize the variables that will be used
    # to store the episode length and episode reward
    self.episode_length = 0
    self.episode_reward = 0
    # ====================== #
  
  def reset(self):
    """
    Reset the environment 
    """
    obs = self.env.reset()
    # === YOUR CODE HERE ===#
    # Reset the variables
    self.episode_length = 0
    self.episode_reward = 0
    # ====================== #
    return obs

  def step(self, action):
    """
    :param action: ([float] or int) Action taken by the agent
    :return: (np.ndarray, float, bool, dict) observation, reward, is the episode over?, additional informations
    """
    obs, reward, done, info = self.env.step(action)
    # === YOUR CODE HERE ===#
    # Update the current episode reward and episode length
    self.episode_length += 1
    self.episode_reward += reward  # not discounted
    
    # ====================== #
    if done:
#     if self.episode_length == 10:  # in order not to wait till end of epidode
        done = True
        # === YOUR CODE HERE ===#
        # Store the episode length and episode reward in the info dict
        info=dict(episode_length=self.episode_length,episode_reward=self.episode_reward)      
        # ====================== #
    return obs, reward, done, info

#### Test your wrapper

In [0]:
# To use LunarLander, you need to install box2d box2d-kengz (pip) and swig (apt-get)
# !pip install box2d box2d-kengz

In [92]:
# env = gym.make("LunarLander-v2")
# env = gym.make("CartPole-v1")
env = gym.make("Pendulum-v0")

# === YOUR CODE HERE ===#
# Wrap the environment
wenv = MyMonitorWrapper2(env)
# Reset the environment
obs=wenv.reset()
# Take random actions in the enviromnent and check
# that it returns the correct values after the end of each episode
done = False
while not done:
    action = wenv.action_space.sample()
    _, reward, done, info = wenv.step(action)
    print(reward)
    
print(info)
# ====================== #

-0.0742531929153721
-0.07442181485452244
-0.10337524224886574
-0.11628103215793728
-0.12386241198911684
-0.189261436910616
-0.21292935730237858
-0.3710129133212439
-0.5515746991270738
-0.8367365282710797
-1.1989826727917532
-1.9201040744193203
-2.9523682445190427
-4.294189138657661
-6.069477407393977
-8.028698785420714
-10.855416071929755
-13.994265098675138
-16.037248923435374
-13.698882591538354
-11.192893073376673
-8.823678541830837
-6.952574806040697
-5.331930687946781
-3.746514161750952
-2.471102083534463
-1.609255817262694
-1.1980914364916964
-0.7282464947884381
-0.4328354535345751
-0.23179745008971725
-0.16214699334832336
-0.1316671356490802
-0.11052059645745196
-0.08218398748166761
-0.05477633305710495
-0.06315247209540947
-0.0789358974245228
-0.08691793162216233
-0.0463522524796387
-0.062345195014431865
-0.07568038131632612
-0.13547507392400626
-0.2117697983480599
-0.2316774242614805
-0.4076791567976239
-0.5049823306730337
-0.6232969962451196
-0.9002161058073958
-1.37468668611

 # Conclusion
 
 In this notebook, we have seen:
 - how to easily save and load a model
 - what is wrapper and what we can do with it
 - how to create your own wrapper

## Wrapper Bonus: changing the observation space: a wrapper for episode of fixed length

In [0]:
from gym.wrappers import TimeLimit

class TimeFeatureWrapper(gym.Wrapper):
    """
    Add remaining time to observation space for fixed length episodes.
    See https://arxiv.org/abs/1712.00378 and https://github.com/aravindr93/mjrl/issues/13.

    :param env: (gym.Env)
    :param max_steps: (int) Max number of steps of an episode
        if it is not wrapped in a TimeLimit object.
    :param test_mode: (bool) In test mode, the time feature is constant,
        equal to zero. This allow to check that the agent did not overfit this feature,
        learning a deterministic pre-defined sequence of actions.
    """
    def __init__(self, env, max_steps=1000, test_mode=False):
        assert isinstance(env.observation_space, gym.spaces.Box)
        # Add a time feature to the observation
        low, high = env.observation_space.low, env.observation_space.high
        low, high= np.concatenate((low, [0])), np.concatenate((high, [1.]))
        env.observation_space = gym.spaces.Box(low=low, high=high, dtype=np.float32)

        super(TimeFeatureWrapper, self).__init__(env)

        if isinstance(env, TimeLimit):
            self._max_steps = env._max_episode_steps
        else:
            self._max_steps = max_steps
        self._current_step = 0
        self._test_mode = test_mode

    def reset(self):
        self._current_step = 0
        return self._get_obs(self.env.reset())

    def step(self, action):
        self._current_step += 1
        obs, reward, done, info = self.env.step(action)
        return self._get_obs(obs), reward, done, info

    def _get_obs(self, obs):
        """
        Concatenate the time feature to the current observation.

        :param obs: (np.ndarray)
        :return: (np.ndarray)
        """
        # Remaining time is more general
        time_feature = 1 - (self._current_step / self._max_steps)
        if self._test_mode:
            time_feature = 1.0
        # Optionnaly: concatenate [time_feature, time_feature ** 2]
        return np.concatenate((obs, [time_feature]))

## Going further - Saving format 

The format for saving and loading models has been recently revamped as of Stable-Baselines (>2.7.0).

It is a zip-archived JSON dump and NumPy zip archive of the arrays:
```
saved_model.zip/
├── data              JSON file of class-parameters (dictionary)
├── parameter_list    JSON file of model parameters and their ordering (list)
├── parameters        Bytes from numpy.savez (a zip file of the numpy arrays). ...
    ├── ...           Being a zip-archive itself, this object can also be opened ...
        ├── ...       as a zip-archive and browsed.
```

## Save and find 

In [93]:
# Create save dir
save_dir = "/tmp/gym/"
os.makedirs(save_dir, exist_ok=True)

model = PPO2('MlpPolicy', 'Pendulum-v0', verbose=0).learn(8000)
model.save(save_dir + "/PPO2_tutorial")

In [94]:
!ls /tmp/gym/PPO2_tutorial*

/tmp/gym/PPO2_tutorial.zip


In [95]:
import zipfile

archive = zipfile.ZipFile("/tmp/gym/PPO2_tutorial.zip", 'r')
for f in archive.filelist:
    print(f.filename)

data
parameters
parameter_list


## Exporting saved models

And finally some futher reading for those who want to export to tensorflowJS or Java.

https://stable-baselines.readthedocs.io/en/master/guide/export.html